config/routes.rb
Rails.application.routes.draw do
  resources :items

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

  def self.week_total(week)
    week_total = 0
    Item.all.each do |item|
      week_no = item.created_at.strftime("%U").to_i
      if (week_no == week)
        week_total += item.amount
      end
    end
    week_total
  end

  def self.find_by_week(week)
		Item.where("created_at >= ? and created_at <= ?", Date.commercial(2014,week), Date.commercial(2014,week + 2))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if (!(params[:opening_balance].to_s.empty?))
      session[:opening_balance] = params[:opening_balance]
    else
      if (session[:opening_balance].to_s.empty?)
        session[:opening_balance] = 650.0
      end
    end
    @opening_balance = session[:opening_balance].to_i
    @week_total =  @opening_balance - Item.week_total(Time.now.strftime('%U').to_f)
    @items = Item.find_by_week(Time.now.strftime('%U').to_i)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url(), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_url(), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div <div class="row">
  <div class="small-12 columns">
    <h3><%= link_to 'New Item', new_item_path %></h1>
  </div>
</div>
<div class="row">
  <div class="small-6 small-text-left columns">
    &nbsp;
  </div>
  <div class="small-2 small-text-right columns">
    <b><%= @opening_balance.to_i %></b>
  </div>
  <div class="small-4 columns">
    &nbsp;
  </div>
</div>

<% opening_balance = @opening_balance %>
<% @items.each do |item| %>
  <div class="row">
    <div class="small-1 small-text-left columns">
      <%= item.created_at.strftime("%a") %>
    </div>
    <div class="small-3 small-text-left columns">
      <%= item.description %>
    </div>
    <div class="small-2 small-text-right columns">
      <%= item.amount.to_i  %>
    </div>
    <div class="small-2 small-text-right columns">
      <%= (opening_balance -= item.amount).to_i %>
    </div>
   <div class="small-2 small-text-right columns">
      <%= link_to 'Edit', edit_item_path(item) %>
    </div>
    <div class="small-2 small-text-left columns">
      <%= link_to 'Delete', item, method: :delete %>
    </div>
  </div>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @item.amount %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>